#!/bin/bash

branch=${CIRCLE_BRANCH:-$(git symbolic-ref --short -q HEAD)}
last_commit_msg=$(git log -1 --pretty=%B)

echo "Last commit: $last_commit_msg"

if [[ $last_commit_msg =~ ^Release\ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
  echo "Release commit. Exiting"
  exit 0
fi

if [ $NPM_TOKEN ]; then
  echo "\$NPM_TOKEN token found. Adding to ~/.npmrc"
  echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
fi

if [ $CI ]; then
  echo 'Setting git CI User'
  git config --global user.email "circleci@wiser.com"
  git config --global user.name "CircleCI Publish"
fi

type=''
opts_preprelease=''

case $branch in
  master)
    type="release"
    ;;
  *beta)
    type="beta"
    opts_preprelease='--preRelease=beta --npm.tag=beta'
    ;;
  *)
    type="feature"
    ;;
esac

echo "Building *$type* branch: $branch"

release-it $1 $2 $3 $4 $5 --force \
  -n --no-require-upstream \
  --src.tagName='version-%s' \
  $opts_preprelease
